### ISSUE TITLE
Profiling doesn't work with `allow_url_fopen=Off`

### ISSUE THREAD

**Issue by alies-dev** [maantje/xhprof-buggregator-laravel#16]
Today I spent about 2h trying to fix xhprof integration and finally found an issue: it seems like HTTP client uses from underlying dependencies uses functionality that depends on `allow_url_fopen` PHP config value.

E.g. Guzzle throws an exception for such cases, making this obvious:

```php
if (\ini_get('allow_url_fopen')) {
    $handler = $handler
        ? Proxy::wrapStreaming($handler, new StreamHandler())
        : new StreamHandler();
} elseif (!$handler) {
    throw new \RuntimeException('GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler.');
}
```

I'm not sure what's better:
 - use another HTTP client
 - improve existing HTTP client dependency
 - document `allow_url_fopen=On` requirements

that's why I created this issue here. Please feel free to close it and solve or report it on a repository you think the best to solve this issue.

Thank you for the package!

**Comment by alies-dev** [comment]
hey @maantje

Can you please take a look to this issue? I solved the same for another package https://github.com/InteractionDesignFoundation/laravel-geoip/pull/35 and can do it for this package or it's dependencies. But I would like to know your opinion on which level we should solve the issue. thank you!

**Comment by maantje** [comment]
Hi @alies-dev,

Apologies for the delay. I will review it this weekend.

Thank you for your patience.

**Comment by maantje** [comment]
Hey @alies-dev,

I reviewed the issue, and I believe the best approach is to replace `NativeHttpClient` with `CurlHttpClient`. The `spiral-packages/profiler` package, which this project depends on, already includes `ext-curl: *`. If someone installs it with `--ignore-platform-reqs`, it should still fail due to [this check](https://github.com/symfony/http-client/blob/1ec24a54d1885b11e862d6ddab31bd6749720d20/CurlHttpClient.php#L71) in `CurlHttpClient`.

What do you think?

**Comment by alies-dev** [comment]
@maantje 
Agree, it solves the issue. Great stuff in https://github.com/maantje/xhprof-buggregator-laravel/pull/18 💪

**Comment by maantje** [comment]
@alies-dev, Thank you for reporting and checking.
